define([], function() {
    var FooterView = {
       "views":{
       	    "orderFoot":{
       	    	"template":"text!commonTemplate/foot/orderFoot.html",
       	    	"func":undefined,
       	    },
	       	"mallFoot":{
	    		   "template":"text!commonTemplate/foot/mallFoot.html",
	    		   "func":{
	    			   "exchange":undefined,
	    			   "buyImmediately":undefined,
                       "addShoppingCart":undefined,
	    		   },
	    		   "data":{
	    		   }
	    	   },
    	   "shopCart":{//购物车底部
    		   "template":"text!commonTemplate/foot/shopCartFoot.html",
    		   "func":{
    			   "allSelect":function($dom){//全选
   						console.log("allSelect");
                    },
    			   "delSelect":function($dom){//删除
   					  console.log("delSelect");
                    },
                   "settlAccounts":function($dom){//结账
   					  console.log("settlAccounts");
                    },
    		   },
    		   "data":{
    		   }
    	   },
    	   "oneButtonFoot":{
    		   "template":"text!commonTemplate/foot/oneButtonFoot.html",
    		   "func":{
    			   "button":undefined
    		   },
    		   "func2":{
    			   "button2":undefined
    		   },
    		   "data":{
    			   "text":"购买"
    		   }
    	   },
    	   "mainFoot":{
    		   "template":"text!commonTemplate/foot/mainFootNew.html",
    		   "data":{
    			   "hash":window.location.hash.substring(1)
    		   },
    		   "func":{
    			   "index":function($dom){
       					DMJS.router.navigate("index/index/index",true);
                    },
                    "userInfo":function(){
                            DMJS.router.navigate("user/personal/userInfo",true);
                    },
                    "more":function(){
                            DMJS.router.navigate("index/index/more",true);
                    },
                    "news":function(){
                    	DMJS.router.navigate("other/message/newsList",true);
                    }
    		   },
    		   "onLoad":function($dom){
    			   var hash=window.location.hash.substring(1);
    			   $dom.find("input").each(function(){
    				   if(hash==$(this).attr("activeHash")){
    					   $(this).attr("checked",true);
    				   }else{
    					   $(this).removeAttr("checked");
    				   }
    			   });
    		   }
    	   }
       }
    };
    return FooterView;
});
